apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bl88xbaup-go
  janus-idp.io/tekton: bl88xbaup-go
  backstage.io/kubernetes-id: bl88xbaup-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bl88xbaup-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
